apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker/docker-compose-third-parties.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-server
  name: admin-server
spec:
  ports:
  - name: "8079"
    port: 8079
    targetPort: 8886
  selector:
    io.kompose.service: admin-server
status:
  loadBalancer: {}
