apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker/docker-compose-third-parties.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: admin-server
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: admin-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker/docker-compose-third-parties.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: admin-server
    spec:
      containers:
      - args:
        - java
        - -jar
        - build/libs/codex-admin-0.1.0.jar
        command:
        - sh
        - -c
        - ./wait-for-it.sh config-server:8081 -t 25 && ./run.sh
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: kubernetes
        image: thetyne/codex-admin
        imagePullPolicy: ""
        name: admin-server
        ports:
        - containerPort: 8886
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
