apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-third-parties.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8888
  selector:
    io.kompose.service: config-server
status:
  loadBalancer: {}
