apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker/docker-compose-third-parties.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: eureka-server
  name: eureka-server
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8887
  selector:
    io.kompose.service: eureka-server
status:
  loadBalancer: {}
